version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: property-renovation-flask:latest
    ports:
      - "5001:5001"

  node-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: property-renovation-node:latest
    ports:
      - "4000:4000"
    depends_on:
      - flask-api
